/**
 * Central Lucide icon registry. Data files reference icons by NAME
 * (string); components resolve them through `getIcon(name)`.
 * Keeping this in one place avoids importing all of lucide everywhere
 * and makes missing icons fail gracefully to a sensible default.
 */
import {
  Apple,
  Bot,
  Boxes,
  Brain,
  Building2,
  BarChart3,
  Circle,
  Clock,
  Cloud,
  Code2,
  Compass,
  CreditCard,
  Database,
  Facebook,
  Film,
  Gauge,
  Globe,
  Headphones,
  Instagram,
  Layers,
  Layout,
  Lightbulb,
  LineChart,
  Linkedin,
  Mail,
  Megaphone,
  MessageSquare,
  Mic,
  MonitorSmartphone,
  Palette,
  PenTool,
  Puzzle,
  Rocket,
  Search,
  Share2,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Target,
  TrendingUp,
  Users,
  Video,
  Workflow,
  Wrench,
} from "lucide-react";

const registry = {
  Apple,
  Bot,
  Boxes,
  Brain,
  Building2,
  Clock,
  Cloud,
  Code2,
  Compass,
  CreditCard,
  Database,
  Facebook,
  Film,
  Gauge,
  Globe,
  Headphones,
  Instagram,
  Layers,
  Layout,
  Lightbulb,
  LineChart,
  Linkedin,
  Mail,
  Megaphone,
  MessageSquare,
  Mic,
  MonitorSmartphone,
  Palette,
  PenTool,
  Puzzle,
  Rocket,
  Search,
  Share2,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Target,
  Users,
  Video,
  Workflow,
  Wrench,
  // Aliases for renamed / newer lucide names used in data
  ChartNoAxesCombined: TrendingUp,
  FileChartColumn: BarChart3,
  TrendingUp,
  Twitter: Share2, // X/Twitter glyph removed in recent lucide; reuse Share2
};

export function getIcon(name) {
  return registry[name] || Circle;
}

export { registry as icons };
