// Builds src/data/catalog.js from the webomindapps HTML mirror.
// Extracts real <title> + meta description for every landing page,
// maps each to a service category, and emits a static catalog the
// Next.js [slug] route generates pages from. Run: node scripts/build-catalog.mjs
import fs from "node:fs";
import path from "node:path";

const MIRROR = "c:/My Web Sites/website/www.webomindapps.com";
const OUT = "c:/cgbcode/it/src/data/catalog.js";

// Slugs that already have dedicated routes or are partials/assets — skip.
const RESERVED = new Set([
  "about", "contact", "services", "careers", "career", "index",
  "blog", "case-studies", "apply", "developer-apply", "figma-apply",
  "thank-you", "thankyou", "sitemap", "privacy-policy", "terms-and-conditions",
  "terms", "404",
]);

const NOISE = new Set(["ganeswar-swain"]);

const isPartial = (slug) =>
  /-header$/.test(slug) ||
  /^new-banner/i.test(slug) ||
  /breadcrumb/i.test(slug) ||
  /header$/.test(slug) ||
  /apply/.test(slug) ||           // job-application pages
  NOISE.has(slug);

const CATEGORY_RULES = [
  // 'agent' alone would match "mAGENTo" — require AI context instead.
  ["ai-agents", ["ai-agent", "ai-chat", "ai-voice", "ai-sales", "chat-agent", "voice-agent", "sales-agent", "support-agent", "chatbot", "conversational-ai", "ecommerce-ai"]],
  ["digital-marketing", ["seo", "aeo", "marketing", "-ads", "ppc", "adword", "google-ad", "facebook-advert", "social-media", "smm", "email-market", "content-writing", "performance", "lead-generation", "link-building"]],
  ["ecommerce-development", ["ecommerce", "e-commerce", "shopify", "woocommerce", "magento", "bigcommerce", "online-store"]],
  ["ui-ux-branding", ["branding", "brand-", "logo", "figma", "ui-ux", "uiux", "ux-", "brochure", "video", "graphic", "motion", "poster", "identity", "image-and", "illustration", "packaging", "catalogue", "creative"]],
  ["mobile-apps", ["android", "ios-", "iphone", "flutter", "react-native", "mobile-app", "-app-", "app-development", "ionic", "swift", "kotlin"]],
];

const CATEGORY_LABEL = {
  "web-development": "Web Development",
  "ai-agents": "AI Automations",
  "digital-marketing": "Digital Marketing",
  "ui-ux-branding": "UI/UX & Branding",
  "ecommerce-development": "E-commerce",
  "mobile-apps": "Mobile Apps",
};

function categorize(slug) {
  for (const [cat, kws] of CATEGORY_RULES) {
    if (kws.some((k) => slug.includes(k))) return cat;
  }
  return "web-development";
}

function locationOf(slug) {
  if (/dubai/.test(slug)) return "Dubai";
  if (/california/.test(slug)) return "California";
  if (/bangalore|bengaluru/.test(slug)) return "Bangalore";
  if (/-uae\b|in-uae/.test(slug)) return "UAE";
  if (/-usa\b|in-usa/.test(slug)) return "USA";
  if (/-india\b|in-india/.test(slug)) return "India";
  if (/toronto|canada/.test(slug)) return "Toronto";
  return null;
}

const rebrand = (s) =>
  s.replace(/Webomindapps/g, "Ribbon IT").replace(/webomindapps/g, "ribbonit");

function decode(s) {
  return s
    .replace(/&amp;/g, "&")
    .replace(/&#39;|&rsquo;|&apos;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&ndash;|&mdash;/g, "–")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function extract(html) {
  const titleM = html.match(/<title>([^<]*)<\/title>/i);
  const descM = html.match(/<meta[^>]*name=["']description["'][^>]*content=["']([^"']*)["']/i);
  return {
    title: titleM ? decode(titleM[1]) : "",
    description: descM ? decode(descM[1]) : "",
  };
}

const files = fs
  .readdirSync(MIRROR)
  .filter((f) => f.toLowerCase().endsWith(".html"));

const seen = new Set();
const catalog = [];

for (const file of files) {
  const slug = file.replace(/\.html$/i, "");
  if (RESERVED.has(slug) || isPartial(slug) || seen.has(slug)) continue;

  let html;
  try {
    html = fs.readFileSync(path.join(MIRROR, file), "utf8");
  } catch {
    continue;
  }
  const { title, description } = extract(html);
  if (!title || title.length < 5) continue; // skip empties / partials

  seen.add(slug);
  const category = categorize(slug);
  const location = locationOf(slug);
  // H1: title without the brand suffix.
  const h1 = rebrand(
    title.replace(/\s*[|\-–»]\s*(Webomindapps|Ribbon IT).*$/i, "").trim() || title
  );
  const eyebrow = location
    ? `${CATEGORY_LABEL[category]} · ${location}`
    : CATEGORY_LABEL[category];

  catalog.push({
    slug,
    title: rebrand(title),
    h1,
    description: rebrand(description) || `${h1} — by Ribbon IT.`,
    category,
    eyebrow,
    location,
  });
}

catalog.sort((a, b) => a.slug.localeCompare(b.slug));

const banner = `/**
 * AUTO-GENERATED by scripts/build-catalog.mjs from the source HTML mirror.
 * ${catalog.length} landing pages — real titles + meta, mapped to a service
 * category. Rendered by app/[slug]/page.js. Do not edit by hand; re-run the
 * script to regenerate.
 */`;

const body =
  `${banner}\n\nexport const catalog = ${JSON.stringify(catalog, null, 2)};\n\n` +
  `export const catalogBySlug = Object.fromEntries(catalog.map((p) => [p.slug, p]));\n\n` +
  `export const CATEGORY_LABEL = ${JSON.stringify(CATEGORY_LABEL, null, 2)};\n\n` +
  `export const catalogByCategory = catalog.reduce((acc, p) => {\n` +
  `  (acc[p.category] ||= []).push(p);\n  return acc;\n}, {});\n`;

fs.writeFileSync(OUT, body);

// Console summary
const byCat = catalog.reduce((a, p) => ((a[p.category] = (a[p.category] || 0) + 1), a), {});
console.log(`Wrote ${catalog.length} pages -> ${OUT}`);
console.log(byCat);
